services:
  ms-transaction-tes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-transaction-tes
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '${PORT}:3003'
    env_file:
      - .env
    networks:
      - shared-network-ms

networks:
  shared-network-ms:
    external: true
